# Generated by Django 6.1.1 on 2026-09-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('ano', models.IntegerField()),
                ('tipo_acervo', models.CharField(choices=[('digital', 'Digital'), ('fisico', 'Físico')], max_length=10)),
                ('categoria', models.CharField(choices=[('000', 'Generalidades e Informação'), ('100', 'Filosofia e Psicologia'), ('200', 'Religião e Teologia'), ('300', 'Ciências Sociais e Direito'), ('400', 'Linguística e Idiomas'), ('500', 'Ciências Puras'), ('600', 'Ciências Aplicadas'), ('700', 'Artes e Recreação'), ('800', 'Literatura'), ('900', 'História e Geografia')], max_length=3)),
            ],
        ),
    ]
