# Generated by Django 6.1.1 on 2026-09-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acervo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('000', 'Generalidades'), ('100', 'Filosofia e Psicologia'), ('200', 'Religião e Teologia'), ('300', 'Ciências Sociais e Direito'), ('400', 'Linguística e Idiomas'), ('500', 'Ciências Puras'), ('600', 'Ciências Aplicadas'), ('700', 'Artes e Recreção'), ('800', 'Literatura'), ('900', 'História e Geografia')], max_length=3),
        ),
        migrations.AlterField(
            model_name='livro',
            name='tipo_acervo',
            field=models.CharField(choices=[('digital', 'Digital'), ('fisico', 'fisico')], max_length=10),
        ),
    ]
